version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: elyas
      POSTGRES_PASSWORD: mycar
      POSTGRES_DB: carsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: elyas@admin.com
      PGADMIN_DEFAULT_PASSWORD: mycar
    ports:
      - "7070:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
